### ISSUE TITLE
Permission denied error

### ISSUE THREAD

**Issue by jpicklyk** [CERIT-SC/puppet-chocolatey_sw#2]
After installing the module on Puppet Open Source 3.7.1 I receive the following errors when running:
sudo puppet agent -t --noop

Removing the module resolves the error.

Info: Retrieving pluginfacts
Error: /File[/var/lib/puppet/facts.d]: Failed to generate additional resources using 'eval_generate': Error 400 on SERVE
R: Permission denied - /etc/puppet/environments/production/modules/chocolatey_sw/metadata.json
Error: /File[/var/lib/puppet/facts.d]: Could not evaluate: Could not retrieve file metadata for puppet://puppet/pluginfa
cts: Error 400 on SERVER: Permission denied - /etc/puppet/environments/production/modules/chocolatey_sw/metadata.json
Wrapped exception:
Error 400 on SERVER: Permission denied - /etc/puppet/environments/production/modules/chocolatey_sw/metadata.json
Info: Retrieving plugin
Error: /File[/var/lib/puppet/lib]: Failed to generate additional resources using 'eval_generate': Error 400 on SERVER: P
ermission denied - /etc/puppet/environments/production/modules/chocolatey_sw/metadata.json
Error: /File[/var/lib/puppet/lib]: Could not evaluate: Could not retrieve file metadata for puppet://puppet/plugins: Err
or 400 on SERVER: Permission denied - /etc/puppet/environments/production/modules/chocolatey_sw/metadata.json
Wrapped exception:
Error 400 on SERVER: Permission denied - /etc/puppet/environments/production/modules/chocolatey_sw/metadata.json
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Permission denied - /etc/puppet/environments/
production/modules/chocolatey_sw/metadata.json at /etc/puppet/environments/production/manifests/site.pp:42 on node puppe
t.ss360labs.net
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

**Comment by vholer** [comment]
I believe there shouldn't be any permission denied errors now. File/directory permissions have been fixed in one of previous releases as well as requirements in module metadata. Please reopen if you still experience this problem.
